# Generated by Django 4.0.4 on 2022-05-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
